### ISSUE TITLE
performance enhancement: server side storage of minimal versions of the fonts

### ISSUE THREAD

**Issue by JohnRDOrazio** [av01d/fontpicker-jquery-plugin#1]
Hello, good work with enhancing the jQuery Fontselect plugin! It has come along quite nicely. The only small issue I can see now is the FOUC, fonts initially load with normal text and then start styling with their own font-family after a few seconds when they have been cached and rendered locally.
The only way I have found for overcoming this issue is by storing a minimal version of the fonts locally. This allows to overcome the FOUC. I have accomplished downloading the latest fonts locally using cURL requests and a google fonts API key, you can see an explanation of how I accomplished it here:
[https://www.bibleget.io/2020/04/released-v5-3-of-the-wordpress-plugin/](https://www.bibleget.io/2020/04/released-v5-3-of-the-wordpress-plugin/)
And you can see it in action here:
[https://youtu.be/zqJqU_5UZ5M](https://youtu.be/zqJqU_5UZ5M)
It would be a nice enhancement to this plugin to add the possibility of integrating server side. I have been using the initial Fontselect plugin by Tom Moor in my project. It would be a nice touch if my server side logic could be integrated into your current Fontpicker plugin.

**Comment by av01d** [comment]
Thanks for your compliments. I won't be implementing any server-side code:

- This is a client side jQuery plugin by design: handling the server side is up to the programmer (that would be you ;-))
- Implementing server side code is complicated: there are too many server side languages (PHP, Java, .Net and many more) to support
- Preventing FOUT for ALL Google fonts, means hosting ALL Google fonts (currently 987) on the server: this is not practical at all, and the benefits (preventing FOUT) are tiny.

You're free to use  and extend this plugin with any server-side functionality you need, it won't be part of this plugin.

**Comment by JohnRDOrazio** [comment]
Actually you don't need to host the full version of the fonts locally, only a minimized version with the characters that make up the name of the font. That's how I accomplished it. So actually it is more practical than it seems, because even when they are rendered client side they are still downloading that information from the Google server.

**Comment by av01d** [comment]
Euhh.... nope. The fontpicker plugin also shows a preview of the font in a sentence the user can enter (default: the quick brown fox...). So... you would need the entire font, as users can type any text to render.
