### ISSUE TITLE
Error on console, regarding getFavorites()

### ISSUE THREAD

**Issue by RobEarls** [av01d/fontpicker-jquery-plugin#10]
`Uncaught TypeError: Cannot read property 'undefined' of undefined`
`    at Fontpicker.getFavorites (jquery.fontpicker.js?ver=102740:5966)`
`    at Fontpicker.toggleModal (jquery.fontpicker.js?ver=102740:5776)`
`    at HTMLDivElement.<anonymous> (jquery.fontpicker.js?ver=102740:5994)`
`    at HTMLDivElement.dispatch (jquery.min.js?ver=3.5.1:2)`
`    at HTMLDivElement.v.handle (jquery.min.js?ver=3.5.1:2)`

When set up with no arguments. e.g.  $('#kfontpicker').fontpicker();

Error appears when click in the input element :-

`<input id="kfontpicker" type="text" />`

The modal pop up appears at the same time as the error.

Not sure how to cure/debug this - It's pretty much out of the box -  I did add a few fonts to favorites (Not sure if you use cookies to store these...)

**Comment by RobEarls** [comment]
Somehow favoriteFonts can have an element set "undefined", which means it can't be split

I don't think this is the proper solution, but my "fix" was to insert a check at 5958....

Was this...

`if (fonts.indexOf(favoriteFonts[f]) == -1) {`
`         fonts.push(favoriteFonts[f]);`
`}`

after fix... 

`if (favoriteFonts[f] == "undefined")  {  /* Skip if set to undefined */`
`	continue;`
` }`

`if (fonts.indexOf(favoriteFonts[f]) == -1) {`
`	fonts.push(favoriteFonts[f]);`
`}`

I've no idea if "undefined" is a valid value for this, so the true solution might be to work out why it is set to "undefined" in the first place.

**Comment by av01d** [comment]
This is indeed a cookie-related issue. Did you perhaps use my old fontpicker (https://github.com/av01d/fontselect-jquery-plugin) before, on the same server? 
I see that both the old (fontselect-jquery-plugin) and the new (fontpicker-jquery-plugin) share the same cookie name.
Can you test the sample page: https://av01d.github.io/fontpicker-jquery-plugin/index.html, Example 1? 
This is the fully default config, just as you have tested on your server. What happens if you click the input box here?
Before hacking the code, I would advise to just clear your cookies first. I'm pretty sure this fixes the issue and it won't ever happen again.

**Comment by RobEarls** [comment]
Ah yes!  I did indeed use the old fontpicker at first.  That would explain it.  :-) 

And the sample page code looks to be working 100%

Thanks very much!
